name: Buduj APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalacja Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Instalacja Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Wygeneruj pliki Androida
        run: flutter create . --platforms=android

      - name: Dodaj uprawnienie do Internetu
        run: |
          sed -i '/<application/i <uses-permission android:name="android.permission.INTERNET"\/>' android/app/src/main/AndroidManifest.xml

      - name: Pobierz pakiety
        run: flutter pub get

      - name: Buduj plik APK
        run: flutter build apk --split-per-abi

      - name: Zapisz plik instalacyjny
        uses: actions/upload-artifact@v4
        with:
          name: Kalkulator-APK
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
